### ISSUE TITLE
«In Categories imageURL is being sent back as a boolean in some cases, it should always be sent back as a string, if there is not url just don't send the property back»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [justuno-com/m1#12]
[upwork.com/messages/rooms/room_e6b2d182b68bdb5e9bf343521534b1b6/story_6228ce680e52cb27a78c9b7b6a36ee66](https://www.upwork.com/messages/rooms/room_e6b2d182b68bdb5e9bf343521534b1b6/story_6228ce680e52cb27a78c9b7b6a36ee66)

**Comment by dmitry-fedyuk** [comment]
It is a particular case of https://github.com/justuno-com/m1/issues/9

**Comment by dmitrii-fediuk** [comment]
Done in [1.1.6](https://github.com/justuno-com/m1/releases/tag/1.1.6).
