### ISSUE TITLE
Replace `getPrice` with `getFinalPrice`

### ISSUE THREAD

**Issue by rcurrington** [justuno-com/m1#54]
In file app/code/community/Justuno/M1/Catalog.php the code is using getPrice in 2 places instead of getFinalPrice.  This is an issue in that the product does not show the price that includes sales/discounts.

**Comment by socks415** [comment]
I believe this file would also need to be updated for the variants
/app/code/community/Justuno/M1/Catalog/Variants.php

**Comment by dmitrii-fediuk** [comment]
Done in [1.6.7](https://github.com/justuno-com/m1/releases/tag/1.6.7)
