### ISSUE TITLE
`updatedSince` should be interpreted in the UTC timezone

### ISSUE THREAD

**Issue by socks415** [justuno-com/m1#55]
the following route produces zero results.
/jumagext/response/catalog?pageSize=20&currentPage=1&updatedSince=2021-03-23 17:00:00

but if I change the hour to 11 so its 2021-03-23 11:00:00
I get results that have "UpdatedAt": "2021-03-23 17:15:10",

**Comment by dmitrii-fediuk** [comment]
Fixed in [1.6.8](https://github.com/justuno-com/m1/releases/tag/1.6.8).
Now `updatedSince` request values are interpreted in the UTC timezone, and the module returns `CreatedAt` and `UpdatedAt` values in the UTC timezone too.
